
GET http://localhost:3000/tasks

###

POST http://localhost:3000/taskAdd
Content-Type: application/json

{
    "id": 61,
    "title": "Sample Title",
    "price": 99.99,
    "description": "Sample Description",
    "category": "Sample Category",
    "image": "sample_image.jpg",
    "sold": true,
    "dateOfSale": "2024-05-06"
  }




###

PUT http://localhost:3000/tasks/60/
Content-Type: application/json

{
    "id":60,
    "title": "Sample Title",
    "price": 99.99,
    "description": "Sample Description",
    "category": "Sample Category",
    "image": "sample_image.jpg",
    "sold": true,
    "dateOfSale": "2024-05-06"
  }

###

DELETE http://localhost:3000/tasks/id/
Content-Type: application/json




### Okay Goto Render Webiste Once
### here you created app.js file but in deployment you wrote index.js

### Go Deployement Once

### Okay Are You clarified?

### yes but why did we deleted node_modules folder

### Some times its happen render will arrange them to our Project. Okay

### Note you get error line Invalid ELF in that cases you can remove node_modules.

### now i understood .

### Hope Your query is cleared from our Side. All the best.

### Yes!

### Bye Daveed.

### Okay byee